; App configuration
[app]
name        = PMSJRP
author      = Carlos A Locatelli Jr <call.jmail@gmail.com>
description = Sistema Python Web2py e Banco Mysql Desenvolvido para gestao da SMAURB
keywords    = Meio Ambiente, Qualidade Ambiental
generator   = Web2py Web Framework
production  = true
toolbar     = false

; Host configuration
[host]
names = localhost:*, 127.0.0.1:*, *:*, *, 10.34.*.*:* , qa.riopreto.sp.gov.br

; db configuration
[db]

uri       = 
migrate   = False
pool_size = 10

; smtp address and credentials
[smtp]
server = smtp.gmail.com:587
sender = call.jmail@gmail.com
login  = username:password
tls    = true
ssl    = true

[scheduler]
enabled   = false
heartbeat = 1

[google]
analytics_id =
