; App configuration
[app]
name        = PM_SJRP
author      = Carlos A Locatelli Jr <call.jmail@gmail.com>
description = Sistema Python Web2py e Banco Mysql Desenvolvido para gestão da SMAURB
keywords    = web2py, python, framework
generator   = Web2py Web Framework
production  = false
toolbar     = false

; Host configuration
[host]
names = localhost:*, 127.0.0.1:*, *:*, *, 10.34.*:*, qa.riopreto.sp.gov.br:*, gmail.com

; db configuration
[db]
uri       = 
migrate   = True
pool_size = 10  

; smtp address and credentials
[smtp]
username = pycharleslll@gmail.com
password = _Lup1312'
server = smtp.gmail.com
sender = pycharleslll@gmail.com
login  = pycharleslll@gmail.com:_Lup1312'
tls    = true
ssl    = true

[scheduler]
enabled   = false
heartbeat = 1

[google]
analytics_id =
